version: '2'
services:
  duchoashop-app:
    image: duchoashop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://duchoashop-mariadb:3306/duchoashop?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_CACHE_REDIS_SERVER=redis://duchoashop-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://duchoashop-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://duchoashop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://duchoashop-elasticsearch:9200
    ports:
      - 8080:8080
  duchoashop-mariadb:
    extends:
      file: mariadb.yml
      service: duchoashop-mariadb
  duchoashop-redis:
    extends:
      file: redis.yml
      service: duchoashop-redis
  duchoashop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: duchoashop-elasticsearch
